{ inputs, ... }:{



  imports = [
      inputs.nixcord.homeManagerModules.nixcord
             ];

  programs.nixcord = {
      enable = true;
    vesktop = {
        enable = true;   };
    openASAR = {
        enable = true;      };
    config = {
        frameless = true;
        disableMinSize = true;
      plugins = {
          alwaysExpandRoles.enable = true;
          biggerStreamPreview.enable = true;
          forceOwnerCrown.enable = true;
          noF1.enable = true;
          noMaskedUrlPaste.enable = true;
          noOnboardingDelay.enable = true;
          noProfileThemes.enable = true;
          noSystemBadge.enable = true;
          noTypingAnimation.enable = true;
          noUnblockToJump.enable = true;
          normalizeMessageLinks.enable = true;
          quickMention.enable = true;
          replyTimestamp.enable = true;
          serverInfo.enable = true;
          showAllMessageButtons.enable = true;
          unsuppressEmbeds.enable = true;
          validReply.enable = true;
          validUser.enable = true;
          voiceChatDoubleClick.enable = true;
          voiceDownload.enable = true;
        anonymiseFileNames = {
            enable = true;
            anonymiseByDefault = true;
            method = "randomCharacters";
            randomisedLength = 7;
            consistent = "image";      };
        betterSettings = {
            enable = true;
            disableFade = true;
            organizeMenu = true;
            eagerLoad = true;      };
        crashHandler = { 
            enable = true;
            attemptToPreventCrashes = true;
            attemptToNavigateToHome = true;      };
        fakeNitro = {
            enable = true;
            enableEmojiBypass = true;
            emojiSize = 48;
            transformEmojis = true;
            enableStickerBypass = true;
            stickerSize = 160;
            transformStickers = true;
            transformCompoundSentence = true;
            enableStreamQualityBypass = true;
            useHyperLinks = true;
            hyperLinkText = "{{NAME}}";
            disableEmbedPermissionCheck = true;      };
        imageZoom = {
            enable = true;
            saveZoomValues = false;
            nearestNeighbour = true;
            square = false;
            zoom = 0.2;
            size = 100.0;
            zoomSpeed = 0.5;      };
        messageLogger = {
            enable = true;
            deleteStyle = "text";
            logDeletes = true;
            collapseDeleted = true;
            logEdits = true;
            inlineEdits = true;
            ignoreBots = false;
            ignoreSelf = false;      };
        moreUserTags = {
            enable = true;
            dontShowForBots = false;
            dontShowBotTag = false;
          tagSettings = {
              webhook = {
                  text = "Webhook";
                  showInChat = true;
                  showInNotChat = true;  };
              owner = {
                  text = "Owner";
                  showInChat = true;
                  showInNotChat = true; };
              administrator = {
                  text = "admin";
                  showInChat = true;
                  showInNotChat = true;      };
              moderatorStaff = {
                  text = "Staff";
                  showInChat = true;
                  showInNotChat = true;      };
              moderator = {
                  text = "Mod";
                  showInChat = true;
                  showInNotChat = true;      };
              voiceModerator = {
                  text = "VC Mod";
                  showInChat = true;
                  showInNotChat = true;      };
              chatModerator = {
                  text = "Chat Mod";
                  showInChat = true;
                  showInNotChat = true;      };      };      };
        newGuildSettings = {
            enable = true;
            guild = true;
            messages = "only@Mentions";
            everyone = true;
            role = true;
            events = true;
            showAllChannels = true;      };
        noMosaic = {
            enable = true;
            inlineVideo = true;      };
        permissionsViewer = {
            enable = true;
            permissionsSortOrder = "highestRole";
            defaultPermissionsDropdownState = true;      };
        pinDMs = {
            enable = true; 
            pinOrder = "custom"; 
            dmSectioncollapsed = true;      };
        platformIndicators = {
            enable = true;
            lists = true;
            badges = true;
            messages = true;
            colorMobileIndicator = false;      };
        reviewDB = {
            enable = true;
            notifyReviews = true;
            showWarning = false;
            hideTimestamps = false;
            hideBlockedUsers = false;      };
        showHiddenChannels = {
            enable = true;
            hideUnreads = true;
            showMode = "plain";
            showHiddenChannels = true;      };
        showHiddenThings = {
            enable = true; 
            showTimeouts = true;
            showInvitesPaused = true;
            showModView = true;
            disableDiscoveryFilters = true;
            disableDisallowedDiscoveryFilters = true;      };
        showMeYourName = {
            enable = true; 
            mode = "user-nick";      };
        showTimeoutDuration = {
            enable = true;
            displayStyle = "ssalggnikool";      };
        silentTyping = {
            enable = true;
            showIcon = true;
            contextMenu = true;
            isEnabled = true;      };
        sortFriendRequests = {
            enable = true;
            showDates = true;      };
        translate = {
            enable = true;
            autoTranslate = true; 
            showChatBarButton = true;      };
        userVoiceShow = {
            enable = true;
            showInUserProfileModal = true; 
            showInMemberList = true; 
            showInMessages = true;      };
        viewIcons = {
            enable = true;
            format = "png"; 
            imgSize = 1024;      };
        volumeBooster = {
            enable = true;
            multiplier = 4;      };      };      };
                      };



}