[log]
enabled = false

[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "none"
show_hidden = true
show_symlink = true
scrolloff = 200

[preview]
wrap = "no"
max_width = 1080
max_height = 1080
image_delay = 0
image_filter = "nearest"
image_qaulity = 75

[opener]
edit = [ { run = 'micro "$@"', block = true, for = "linux" }, ]

[input]
cursor_blink = false