c.colors.completion.category.bg = dark3
c.colors.completion.category.border.bottom = dark3
c.colors.completion.category.border.top = dark3
c.colors.completion.category.fg = light1
c.fonts.completion.category = 'bold default_size default_family'
c.colors.completion.even.bg = dark4
c.colors.completion.odd.bg = dark4
c.colors.completion.fg = [ dark1, dark1, dark1 ]
c.colors.completion.item.selected.bg = light1
c.colors.completion.item.selected.border.bottom = dark1
c.colors.completion.item.selected.border.top = dark1
c.colors.completion.item.selected.fg = dark6
c.colors.completion.item.selected.match.fg = light7
c.colors.completion.match.fg = light7
c.colors.completion.scrollbar.bg = clear
c.colors.completion.scrollbar.fg = clear
c.fonts.completion.entry = 'default_size default_family'

c.completion.cmd_history_max_items = 9
c.completion.delay = 0
c.completion.favorite_paths = [ ]
c.completion.height = '30%'
c.completion.min_chars = 1
c.completion.open_categories = [ 'bookmarks', 'quickmarks', 'history' ]
c.completion.quick = False
c.completion.scrollbar.padding = 0
c.completion.scrollbar.width = 0
c.completion.show = 'always'
c.completion.shrink = True
c.completion.timestamp_format = '%m-%d-%Y %H:%M'
c.completion.use_best_match = False
c.completion.web_history.exclude = [ ]
c.completion.web_history.max_items = 243