[manager]

keymap = [

	{ on = "<Esc>",   run = "escape",   desc = "Exit visual mode, clear selected, or cancel search" },
	{ on = "<C-q>",   run = "quit",     desc = "Quit the process" },

	# Hopping
	{ on = "<Up>",       run = "arrow -1",      desc = "Move cursor up" },
	{ on = "<Down>",     run = "arrow 1",       desc = "Move cursor down" },

	{ on = "<S-Up>",     run = "seek -5",   desc = "Seek up 5 units in the preview" },
	{ on = "<S-Down>",   run = "seek 5",    desc = "Seek down 5 units in the preview" },

	{ on = "<C-Up>",     run = "arrow -100%",   desc = "Move cursor up one page" },
	{ on = "<C-Down>",   run = "arrow 100%",    desc = "Move cursor down one page" },

	# Navigation
	{ on = "<Left>",    run = "leave",   desc = "Go back to the parent directory" },
	{ on = "<Right>",   run = "enter",   desc = "Enter the child directory" },

  { on = [ "<C-g>", "/" ],   run = "cd --interactive",   desc = "Goto Directory" },
	{ on = [ "<C-g>", "n" ],   run = "cd /etc/nixos",      desc = "Goto Nixos" },
  { on = [ "<C-g>", "h" ],   run = "cd ~",               desc = "Go Home" },

	# Details
	{ on = "<Tab>",   run = "spot",   desc = "Information" },

	# Operation
	{ on = "<Enter>",   run = "open",                         desc = "Open selected files" },
	{ on = [ "<C-o>", "d" ],     run = "remove --permanently",         desc = "Permanently delete selected files" },
	{ on = [ "<C-o>", "c" ],     run = "create",                       desc = "Create a file (ends with / for directories)" },
	{ on = [ "<C-o>", "r" ],     run = "rename --cursor=before_ext",   desc = "Rename selected file(s)" },

	# Linemode
	{ on = [ "<C-m>", "c" ],   run = "linemode btime",         desc = "Show Creation Time" },
	{ on = [ "<C-m>", "m" ],   run = "linemode mtime",         desc = "Show Modified Time" },
	{ on = [ "<C-m>", "n" ],   run = "linemode none",          desc = "None" },
	{ on = [ "<C-m>", "o" ],   run = "linemode owner",         desc = "Show Owner" },
	{ on = [ "<C-m>", "p" ],   run = "linemode permissions",   desc = "Show Permissions" },
	{ on = [ "<C-m>", "s" ],   run = "linemode size",          desc = "Show Size" },
	{ on = [ "<C-m>", "h" ],   run = "hidden toggle",          desc = "Show Hidden" },

	# Copy
	{ on = [ "<C-c>", "p" ],   run = "copy path",       desc = "Path To File" },
	{ on = [ "<C-c>", "d" ],   run = "copy dirname",    desc = "Directory Containing File" },
	{ on = [ "<C-c>", "f" ],   run = "copy filename",   desc = "Filename" },

	# Search
  { on = [ "<C-s>", "s" ],   run = "search --via=fd",         desc = "Search" },
	{ on = [ "<C-s>", "f" ],   run = "find --smart",            desc = "Find" },
	{ on = "<Right>",          run = "find_arrow",              desc = "Find Next" },
	{ on = "<Left>",           run = "find_arrow --previous",   desc = "Find Previous" },

	# Sorting
	{ on = [ "<C-f>", "c" ],   run = [ "sort btime --reverse=no", "linemode btime" ],   desc = "Sort By Creation Time" },
	{ on = [ "<C-f>", "m" ],   run = [ "sort mtime --reverse=no", "linemode mtime" ],   desc = "Sort By Modified time" },
  { on = [ "<C-f>", "s" ],   run = [ "sort size --reverse=no", "linemode size" ],     desc = "Sort By Size" },

	{ on = [ "<C-f>", "." ],   run = "sort extension --reverse=no",   desc = "Sort By File Type" },

	{ on = [ "<C-f>", "a" ],   run = "sort alphabetical --reverse=no",   desc = "Sort Alphabetically" },
	{ on = [ "<C-f>", "n" ],   run = "sort natural --reverse=no",        desc = "Sort Naturally" },

]

 ##################################################

[spot]

keymap = [

	{ on = "<Esc>",     run = "close",      desc = "Close the spot" },
	{ on = "<Up>",      run = "arrow -1",   desc = "Move cursor up" },
	{ on = "<Down>",    run = "arrow 1",    desc = "Move cursor down" },
	{ on = "<Left>",    run = "swipe -1",   desc = "Swipe to the next file" },
	{ on = "<Right>",   run = "swipe 1",    desc = "Swipe to the previous file" },

]

 ##################################################

[pick]

keymap = [

	{ on = "<Esc>",     run = "close",            desc = "Cancel pick" },
	{ on = "<Enter>",   run = "close --submit",   desc = "Submit the pick" },

	{ on = "<Up>",     run = "arrow -1",   desc = "Move cursor up" },
	{ on = "<Down>",   run = "arrow 1",    desc = "Move cursor down" },

]

 ##################################################

[input]

keymap = [

	{ on = "<Enter>",   run = "close --submit",   desc = "Submit input" },
	{ on = "<Esc>",     run = "escape",           desc = "Go back the normal mode, or cancel input" },

	# Undo/Redo
	{ on = "<C-z>",   run = "undo",   desc = "Undo" },
	{ on = "<C-Z>",   run = "redo",   desc = "Redo" },

]

 ##################################################

[confirm]

keymap = [

	{ on = "<Esc>",     run = "close",            desc = "Cancel the confirm" },
	{ on = "<Enter>",   run = "close --submit",   desc = "Submit the confirm" },

	{ on = "n",   run = "close",            desc = "Cancel the confirm" },
	{ on = "y",   run = "close --submit",   desc = "Submit the confirm" },

	{ on = "<Up>",     run = "arrow -1",   desc = "Move cursor up" },
	{ on = "<Down>",   run = "arrow 1",    desc = "Move cursor down" },

]

[completion]

keymap = [

	{ on = "<Tab>",     run = "close --submit",                               desc = "Submit the completion" },
	{ on = "<Enter>",   run = [ "close --submit", "close_input --submit" ],   desc = "Submit the completion and input" },

	{ on = "<Up>",     run = "arrow -1",   desc = "Move cursor up" },
	{ on = "<Down>",   run = "arrow 1",    desc = "Move cursor down" },

]

 ##################################################
