[general]
working_directory = "None"

[window]
decorations = "None"
opacity = 1.0
blur = false
startup_mode = "Windowed"

[scrolling]
history = 10000
miltiplier = 3

[font]
normal = { family = "0xProtoNerdFontMono", style = "Regular" }
bold = { family = "0xProtoNerdFontMono", style = "Bold" }
italic = { family = "0xProtoNerdFontMono", style = "Italic" }
bold_italic = { family = "0xProtoNerdFontMono", style = "Italic" }
size = 11.0

[colors]
foreground = #DEDEDE
background = #222222
dim_foreground = #C0C0C0
bright_foreground = #F1F1F1
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }
indexed_colors = [{ index = <integer>, color = "<string>" },]
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.dim]
black = "#0f0f0f"
red = "#C02020"
yellow = "#C0C030"
green = "#30C030"
cyan = "#30C0C0"
blue = "#0060C0"
magenta = "#C030C0"
white = "#C0C0C0"

[colors.normal]
black = "#222222"
red = "#E03030"
yellow = "#E0E030"
green = "#30E030"
cyan = "#30E0E0"
blue = "#3030E0"
magenta = "#E060E0"
white = "#DEDEDE"

[colors.bright]
black = "#404040"
red = "#FF0000"
yellow = "#FFFF00"
green = "#00FF00"
cyan = "#00FFFF"
blue = "#0000FF"
magenta = "#FF00FF"
white = "#F1F1F1"

[bell]
animation = "Linear"
duration = 0
#color = "#ffffff"
#command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

