[general]
working_directory = "None"

[window]
decorations = "None"
opacity = 1.0
blur = false
startup_mode = "Windowed"

[scrolling]
history = 10000
miltiplier = 3

[font]
normal = { family = "0xProtoNerdFontMono", style = "Regular" }
bold = { family = "0xProtoNerdFontMono", style = "Bold" }
italic = { family = "0xProtoNerdFontMono", style = "Italic" }
bold_italic = { family = "0xProtoNerdFontMono", style = "Italic" }
size = 11.0

[colors]
foreground = #
background = #
dim_foreground = #
bright_foreground = #
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }
indexed_colors = [{ index = <integer>, color = "<string>" },]
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.dim]
black = "#0f0f0f"
red = "#712b2b"
green = "#5f6f3a"
yellow = "#a17e4d"
blue = "#456877"
magenta = "#704d68"
cyan = "#4d7770"
white = "#8e8e8e"

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"

[bell]
animation = "Linear"
duration = 0
#color = "#ffffff"
#command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

