[debug]
render_timer = false
persistent_logging = false
log_level = "off"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = true

[general]
working_directory = "None"
live_config_reload = true

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "None"
opacity = 1.0
blur = false
startup_mode = "Windowed"
level = "Normal"

[scrolling]
history = 10000
miltiplier = 3

[font.normal]
family = "0xProtoNerdFontMono"

[font]
size = 11.0

[colors]
background = "#262626"
foreground = "#D9D9D9"
dim_foreground = "#8C8C8C"
bright_foreground = "#F2F2F2"
cursor = { text = "#262626", cursor = "#D9D9D9" }

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.dim]
black = "#262626"
red = "#CC6666"
yellow = "#CCCC66"
green = "#66CC66"
cyan = "#66CCCC"
blue = "#6666CC"
magenta = "#CC66CC"
white = "#999999"

[colors.normal]
black = "#262626"
red = "#FF8080"
yellow = "#FFFF80"
green = "#80FF80"
cyan = "#80FFFF"
blue = "#8080FF"
magenta = "#FF80FF"
white = "#BFBFBF"

[colors.bright]
black = "#262626"
red = "#FF8080"
yellow = "#FFFF80"
green = "#80FF80"
cyan = "#80FFFF"
blue = "#8080FF"
magenta = "#FF80FF"
white = "#E6E6E6"

[bell]
animation = "Linear"
duration = 0
#color = "#ffffff"
#command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = "None"
blink_interval = 750
unfocused_hollow = true
thickness = 0.15

[terminal]
shell = "bash"
osc52 = "CopyPaste"

[mouse]
hide_when_typing = false

[keyboard]


[hints]
alaphabet = "jfkdls;ahgurieowpq"

