{





  programs = {
    firefox = {
      policies = {
        Preferences = {
            accessibility.AOM.enabled = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.ARIAElementReflection.enabled = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.accesskeycausesactivation = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.blockautorefresh = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.browsewithcaret = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.browsewithcaret_shortcut.enabled = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.warn_on_browsewithcaret = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.enable_all_cache_domains = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.force_disabled = {
                Value = 1;
                Type = "number";
                Status = "locked";      };
            accessibility.monoaudio.enable = {
                Value = true;
                Type = "boolean";
                Status = "locked";      };
            accessibility.mouse_focuses_formcontrol = {
                Value = 0;
                Type = "number";
                Status = "locked";      };
            accessibility.tabfocus = {
                Value = 7;
                Type = "number";
                Status = "locked";      };
            accessibility.tabfocus_applies_to_xul = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.typeaheadfind = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.typeaheadfind.autostart = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.typeaheadfind.casesensitive = {
                Status = "clear";      };
            accessibility.typeaheadfind.enablesound = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.typeaheadfind.flashBar = {
                Value = 0;
                Type = "number";
                Status = "locked";      };
            accessibility.typeaheadfind.linksonly = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.typeaheadfind.manual = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.typeaheadfind.matchesCountLimit = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.typeaheadfind.prefillwithselection = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.typeaheadfind.soundURL = {
                Status = "clear";      };
            accessibility.typeaheadfind.startlinksonly = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.typeaheadfind.timeout = {
                Value = 10000;
                Type = "number";
                Status = "locked";      };
            accessibility.uia.enable = {
                Value = false;
                Type = "boolean";
                Status = "locked";      };
            accessibility.windows.suppress-after-clipboard-copy = {
                Value = 0;
                Type = "number";
                Status = "locked";      };
            accessibility.windows.suppress-for-snap-layout = {
                Value = 0;
                Type = "number";
                Status = "locked";      };
